docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$PRIVATE_REGISTRY_USER" -p "$PRIVATE_REGISTRY_PASSWORD" $PRIVATE_REGISTRY
  script:
      - docker pull $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:latest || true
      - docker build --cache-from $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:latest --tag $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:latest .
      - docker push $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      - docker push $PRIVATE_REGISTRY/$CI_REGISTRY_IMAGE:latest
  only:
    - master
